name: Gradle CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push and pull request events but only for the master branch
  push:
    paths-ignore:
      - '**/*.md'
      - '**/LICENSE'
  pull_request:
    paths-ignore:
      - '**/*.md'
      - '**/LICENSE'

  # Allows to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  build:

    name: Gradle-Build
    
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v3

      # Setup JDK
      - name: Setup Java JDK
        uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: 'zulu'
          cache: 'gradle'

      # Validate Gradle Wrapper
      - name: Gradle Wrapper Validation
        uses: gradle/wrapper-validation-action@v1.0.5

      # Build
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Build with Gradle
        run: ./gradlew buildPlugin
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: "yzl-vanilla-build"
          # Directory containing files to upload
          path: build/mirai/

      # Count code via cloc
      - name: Cloc
        run: |
          sudo apt install cloc
          cloc . > cloc_results.txt
          echo '### 🔥 Cloc Results 🔥' >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          cat cloc_results.txt >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY